global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'server-metrics'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'nginx-metrics'
    static_configs:
      - targets: ['nginx-exporter:9113']
########################## MAVEN PROJECTS #############################################
  - job_name: 'b2b-api-apps'
    metrics_path: '/b2b/actuator/prometheus' # Set the custom metrics path
    static_configs:
      - targets:
        - 'b2b-auth-service:6061'
        - 'b2b-banners-service:6062'
        - 'b2b-cart-service:6063'
        - 'b2b-checkout-service:6064'
        - 'b2b-fcm-service:6065'
        - 'b2b-oms-service:6066'
        - 'b2b-product-service:6067'
